"""add bookings and payments tables

Revision ID: 3af698e4c682
Revises: d08a674d9803
Create Date: 2026-02-18 20:34:01.812350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3af698e4c682'
down_revision: Union[str, Sequence[str], None] = 'd08a674d9803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedure_categories',
    sa.Column('name_ko', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('name_ja', sa.String(length=100), nullable=True),
    sa.Column('name_zh', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['procedure_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('procedures',
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('name_ko', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=True),
    sa.Column('name_ja', sa.String(length=200), nullable=True),
    sa.Column('name_zh', sa.String(length=200), nullable=True),
    sa.Column('name_vi', sa.String(length=200), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description_ko', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('effects_ko', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('effect_duration', sa.String(length=100), nullable=True),
    sa.Column('downtime_days', sa.Integer(), nullable=True),
    sa.Column('min_interval_days', sa.Integer(), nullable=True),
    sa.Column('common_side_effects', sa.Text(), nullable=True),
    sa.Column('rare_side_effects', sa.Text(), nullable=True),
    sa.Column('dangerous_side_effects', sa.Text(), nullable=True),
    sa.Column('precautions_before', sa.Text(), nullable=True),
    sa.Column('precautions_during', sa.Text(), nullable=True),
    sa.Column('precautions_after', sa.Text(), nullable=True),
    sa.Column('pain_level', sa.Integer(), nullable=True),
    sa.Column('pain_type', sa.String(length=100), nullable=True),
    sa.Column('anesthesia_options', sa.Text(), nullable=True),
    sa.Column('anesthesia_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['procedure_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('clinic_procedures',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('procedure_id', sa.Uuid(), nullable=False),
    sa.Column('custom_description', sa.Text(), nullable=True),
    sa.Column('custom_effects', sa.Text(), nullable=True),
    sa.Column('custom_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('custom_effect_duration', sa.String(length=100), nullable=True),
    sa.Column('custom_downtime_days', sa.Integer(), nullable=True),
    sa.Column('custom_min_interval_days', sa.Integer(), nullable=True),
    sa.Column('custom_precautions_before', sa.Text(), nullable=True),
    sa.Column('custom_precautions_during', sa.Text(), nullable=True),
    sa.Column('custom_precautions_after', sa.Text(), nullable=True),
    sa.Column('custom_pain_level', sa.Integer(), nullable=True),
    sa.Column('custom_anesthesia_options', sa.Text(), nullable=True),
    sa.Column('cross_sell_procedure_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('upsell_procedure_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('incompatible_procedure_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('sequence_notes', sa.Text(), nullable=True),
    sa.Column('material_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('difficulty_score', sa.Integer(), nullable=True),
    sa.Column('clinic_preference', sa.Integer(), nullable=True),
    sa.Column('sales_performance_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('clinic_preference BETWEEN 1 AND 3', name='ck_preference'),
    sa.CheckConstraint('difficulty_score BETWEEN 1 AND 5', name='ck_difficulty'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinic_id', 'procedure_id')
    )
    op.create_index(op.f('ix_clinic_procedures_clinic_id'), 'clinic_procedures', ['clinic_id'], unique=False)
    op.create_table('bookings',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('clinic_procedure_id', sa.Uuid(), nullable=True),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('booking_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('remaining_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['clinic_procedure_id'], ['clinic_procedures.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_clinic_id'), 'bookings', ['clinic_id'], unique=False)
    op.create_table('procedure_pricing',
    sa.Column('clinic_procedure_id', sa.Uuid(), nullable=False),
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('regular_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('event_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('event_start_date', sa.Date(), nullable=True),
    sa.Column('event_end_date', sa.Date(), nullable=True),
    sa.Column('is_package', sa.Boolean(), nullable=False),
    sa.Column('package_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prices_by_currency', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('discount_warning', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['clinic_procedure_id'], ['clinic_procedures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procedure_pricing_clinic_id'), 'procedure_pricing', ['clinic_id'], unique=False)
    op.create_table('payments',
    sa.Column('clinic_id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('pg_provider', sa.String(length=50), nullable=True),
    sa.Column('pg_payment_id', sa.String(length=200), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_link', sa.String(length=500), nullable=True),
    sa.Column('qr_code_url', sa.String(length=500), nullable=True),
    sa.Column('link_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_clinic_id'), 'payments', ['clinic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_clinic_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_procedure_pricing_clinic_id'), table_name='procedure_pricing')
    op.drop_table('procedure_pricing')
    op.drop_index(op.f('ix_bookings_clinic_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_clinic_procedures_clinic_id'), table_name='clinic_procedures')
    op.drop_table('clinic_procedures')
    op.drop_table('procedures')
    op.drop_table('procedure_categories')
    # ### end Alembic commands ###
